title: Khatun A Jannat Chowdhury
description: Research Associate in Technology Management
theme: jekyll-theme-minimal
logo: /77e09929-f640-4285-ab0b-f5f47e5044c2.jpg

# Custom sidebar elements
avatar: /77e09929-f640-4285-ab0b-f5f47e5044c2.jpg
email: jannatchowdhury01@gmail.com
cv_link: /Khatun A Jannat Chowdhury_Academic CV.pdf
github_username: jannatchowdhury
